# Docker compose file for the SNMP Prometheus + Grafana monitoring
# v.1.2
# Prometheuse URL:    [IP]:9090/targets
# Node exportter URL: [IP]:9100
# SNMP exporter URL:  [IP]:9116
# 
# Denis Chertkov, denis@chertkov.info, 20241215

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=90d
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "UTC"
    networks:
      - default

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: node-exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "UTC"
    networks:
      - default

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "UTC"
    networks:
      - default

  snmp-exporter:
    image: prom/snmp-exporter
#    volumes:
#      - ./snmp_generator/snmp.yml:/etc/snmp_exporter/snmp_exporter/snmp.yml
    container_name: snmp-exporter
    hostname: snmp-exporter
    ports:
      - 9116:9116
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
