global:
    scrape_interval: 30s
    scrape_timeout: 25s

scrape_configs:
  - job_name: node
    scrape_interval: 30s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'snmp'
    scrape_interval: 15s
    static_configs:
    - targets:
#	DC11
      - 10.10.254.100
      - 10.10.254.101
      - 10.10.254.102
#	SE2
      - 10.11.254.100
      - 10.11.254.101
      - 10.11.254.102
    metrics_path: /snmp
    params:
        auth: [public_v2]
        module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: []
        target_label: __address__
        replacement: 'snmp-exporter:9116'
